import os
from pathlib import Path

from langchain.agents import create_agent
from langchain_core.tools import tool
from langchain_ollama import ChatOllama

from app.services.log_service import count_log_levels, read_log_file


DEFAULT_MODEL = "qwen3.6:latest"
OLLAMA_BASE_URL = "http://localhost:11434"


SYSTEM_PROMPT = (
    "You are a DevOps log analysis assistant. "
    "Use only the information provided in the log content and the deterministic "
    "statistics generated by the Python application. "
    "Never invent events, causes, infrastructure details, or statistics. "
    "Always use the analyze_log_file tool to obtain the exact INFO, WARNING, "
    "and ERROR counts. "
    "State the exact counts first. "
    "Then explain what the actual log entries indicate. "
    "When making an inference, clearly label it as an inference. "
    "Do not introduce hypothetical examples that are not present in the log. "
    "Suggest investigation ideas only when they are directly supported by the "
    "actual log entries. "
    "Never claim that an action was performed."
)


@tool
def analyze_log_file(path: str) -> str:
    """Read a log file and return exact INFO, WARNING and ERROR counts."""
    text = read_log_file(path)
    counts = count_log_levels(text)

    return ", ".join(
        f"{level}={counts[level]}"
        for level in ("INFO", "WARNING", "ERROR")
    )


def get_model_name() -> str:
    """Return the configured Ollama model name."""
    return os.environ.get("OLLAMA_MODEL", DEFAULT_MODEL)


def make_agent():
    """Create the local DevOps log-analysis agent."""
    model = ChatOllama(
        model=get_model_name(),
        base_url=OLLAMA_BASE_URL,
        temperature=0,
    )

    return create_agent(
        model,
        tools=[analyze_log_file],
        system_prompt=SYSTEM_PROMPT,
    )


_agent = None


def get_agent():
    """Create the agent once and reuse it for subsequent requests."""
    global _agent

    if _agent is None:
        _agent = make_agent()

    return _agent


def analyze_logs_with_ai(path: str | Path) -> dict:
    """
    Analyze a log file using deterministic Python statistics and a local LLM.
    """
    log_path = Path(path)

    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")

    if not log_path.is_file():
        raise ValueError(f"Log path is not a file: {log_path}")

    text = read_log_file(log_path)
    counts = count_log_levels(text)

    agent = get_agent()

    prompt = (
        f"Analyze this DevOps log file: {log_path}\n\n"
        "Use the analyze_log_file tool first to verify the exact counts.\n\n"
        "Here is the complete log content. Use only this content when "
        "explaining what happened:\n\n"
        f"{text}"
    )

    result = agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                }
            ]
        },
        {"recursion_limit": 10},
    )

    messages = result.get("messages", [])

    if not messages:
        raise RuntimeError("AI agent returned no messages.")

    analysis = messages[-1].content

    if not isinstance(analysis, str):
        analysis = str(analysis)

    return {
        "log_file": str(log_path),
        "counts": counts,
        "analysis": analysis.strip(),
        "model": get_model_name(),
    }